### ISSUE TITLE
Bencoding.BenDictionary misleading name

### ISSUE THREAD

**Issue by StefanMich** [deaddog/BitTorrent#10]
It is named dictionary, but a List is underneath. 
This might be misleading 

Should either be renamed or the internal representation should be changed

**Comment by deaddog** [comment]
It was done to ensure that the order of the elements in the dictionary is maintained. I am not sure about the behaviour of the .Net Dictionary. I will look into it.

**Comment by deaddog** [comment]
The .Net Dictionary does not guarantee that order is maintained, which is important when generating info hash.
See http://stackoverflow.com/a/4007787
