### ISSUE TITLE
Implement SetPriority and SetPriorityAll in qBitTorrentClient

### ISSUE THREAD

**Issue by deaddog** [deaddog/BitTorrent#8]

**Comment by StefanMich** [comment]
What is the expected outcome of SetPriorityAll? The resulting order is random as far is I can figure out

**Comment by deaddog** [comment]
Return a constant (either one) and wait for someone to finish #11. Or just do #11.

**Comment by StefanMich** [comment]
The question is more about what is expected of the torrent queue. When the queue starts out as

1: X
2: Y
3: Z

and you run SetPriorityAll, what do you expect will happen? As all torrents need different priorities (at least in QB), the resulting order will be either the same as before SetPriorityAll or some other pseudo random order.

Is it ever a useful command?

**Comment by deaddog** [comment]
Ahh yes, forgot about that. We have to redefine the priority methods. I would suggest four methods:
- MoveUp
- MoveDown
- MoveTop
- MoveBottom

All of them should accept a collection of torrents (like the other IClient methods) and there should be no priority methods for all torrents.

**Comment by StefanMich** [comment]
This describes the current SetPriority method.
Closing issue and deleting SetPriorityAll
