### ISSUE TITLE
static InfoHash using peculiar string

### ISSUE THREAD

**Issue by StefanMich** [deaddog/BitTorrent#9]
the string table reads as follows:

string table = "abcdefghijklmnopqrstuvwxyz234567";

I do not know if it will ever be a problem but the '1' is omitted.
If this is not intended it could cause confusion

**Comment by deaddog** [comment]
This is the Base32 definition:
https://en.wikipedia.org/wiki/Base32#RFC_4648_Base32_alphabet
I will insert a comment in code.
